### ISSUE TITLE
Proteomics experiments plot view images are not appearing

### ISSUE THREAD

**Issue by ke4** [ebi-gene-expression-group/atlas-web-bulk#164]
In the Bulk staging environment(wp-p1m2-98) issue:

1. `click on any proteomics experiments ex: E-PROT-68.
2. Then choose the plots tab, then click on the plots tab.
3. Click on any plots for the view like GO, Reactome..etc. You will see a blank page. 
4. But the expected result should be a PNG image with some details.

**Comment by ke4** [comment]
@upendrakumbham tested it in the test environment and it works properly there.
She also used the same WAR file in staging, but it was not working.
It looks like not a code issue.
@upendrakumbham is going to compare staging and test environment configuration and then set up a meeting with Data Prod Team.

**Comment by upendrakumbham** [comment]
Config files look the same, I don't see any differences between staging and test Bulk environments.

**Comment by upendrakumbham** [comment]
During debugging, I realized that the temp directory was missing from this path: `/nfs/public/rw/homes/tc_fg02/tomcat/tomcat8/temp`

Here is the error trace:

```
INFO: Initializing Spring DispatcherServlet 'dispatcher'
Nov 21, 2023 4:28:41 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [dispatcher] in context with path [/gxa] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: javax.imageio.IIOException: Can't create cache file!] with root cause
java.nio.file.NoSuchFileException: /nfs/public/rw/homes/tc_fg02/tomcat/tomcat8/temp/imageio1524780011239992754.tmp
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:215)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
	at java.base/java.nio.file.Files.createFile(Files.java:647)
	at java.base/java.nio.file.TempFileHelper.create(TempFileHelper.java:137)
	at java.base/java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:160)
	at java.base/java.nio.file.Files.createTempFile(Files.java:912)
	at java.desktop/javax.imageio.stream.FileCacheImageInputStream.<init>(FileCacheImageInputStream.java:102)
```

-  Application was trying to write some  `imagexxxxx.tmp` files into this temp directory before passing to front end to view the plat images.

**Comment by upendrakumbham** [comment]
Issue was resolved by creating missing temp directroy under the above path.So, closing this issue.

**Comment by upendrakumbham** [comment]
Issue resolved, hence closing this issue.
